builds:
  -
    main: ./cmd/main.go
    binary: stas
    goos:
      - linux
      - darwin
      - windows
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
archives:
  -
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - scripts/aws
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^refactor'
    - typo
