version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15

    steps:
      - checkout

      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.37.0

      - run: make lint
      - run: make testrace
      - run: make testaccmock
